### ISSUE TITLE
Squid5.2-openssl package for Ubuntu 20.04LTS on Raspberry Pi4

### ISSUE THREAD

**Issue by aspx1981** [diladele/squid-ubuntu#15]
Hello,

your guide is very useful, but I tried to use it with my Raspberry Pi4 and I got always a new dependency error.

Could you help me pls ?

do you have same package squid5.2-openssl for Raspberry Pi4 ?

Thanks a lot

**Comment by ra-at-diladele-com** [comment]
Sorry for now we did drop support for running Web Safety 8.0 (and thus Squid 5) on Raspberry PI :( so I cannot offer any help on that matter :(
