### ISSUE TITLE
Squid 5.2 memory leak

### ISSUE THREAD

**Issue by danieljloughlin** [diladele/squid-ubuntu#16]
We are seeing a significant memory leak in Squid 5.2 - appears to be this issue https://bugs.squid-cache.org/show_bug.cgi?id=5132, which has been fixed in 5.4.

![image](https://user-images.githubusercontent.com/38425697/160163844-13d18fd4-5322-4d5d-bbc7-c194d820b796.png)

I would caution anyone upgrading to Websafety 8 from 7.9 in high usage environments due to this.

**Comment by ra-at-diladele-com** [comment]
We track Debian 11 - so when they have 5.4 we will integrate it asap.

**Comment by ra-at-diladele-com** [comment]
Added related issue at https://github.com/diladele/websafety/issues/1787

**Comment by ra-at-diladele-com** [comment]
5.7 seems to be fine regarding memory leaks. Closing.
