### ISSUE TITLE
request upgrade

### ISSUE THREAD

**Issue by maravento** [diladele/squid-ubuntu#19]
great project. can you upgrade to v5.7 for ubuntu 22.04 LTS?

Note: in reference to the [debian tracker](https://tracker.debian.org/pkg/squid) unstable ends at 5.6. Now 5.7 is an stable version (Ubuntu 22.04 install 5.2 by default)

Thanks

**Comment by ra-at-diladele-com** [comment]
Yes will do when moving to Web Safety 8.3 (project starts in Oct).
