### ISSUE TITLE
Upgrade squid 4 to squid 5

### ISSUE THREAD

**Issue by ICTAddict** [diladele/squid-ubuntu#20]
This isn't a bug, but I couldn't find a 'help wanted' label.

I've followed the steps provided here to install squid 4.13 on Ubuntu Server 20.04.
How do I upgrade to squid 5.5?
I think I should remove this file `/etc/apt/sources.list.d/squid413-ubuntu20.diladele.com.list`
before adding the source for 5.5, right?
what else do I have to do?

Also, I would like to keep the old cache from squid 4.13 if there's a way to do that, because my internet is slow and limited.

Thanks.

**Comment by ra-at-diladele-com** [comment]
I have not tried this actually - but it seems your understanding is correct.
```
apt update
apt upgrade
```
I think cache dir is preserved - but never tried.

**Comment by ICTAddict** [comment]
Thank you! It worked.

At first, the log didn't show any cache hits, so I looked at squid documentation `https://wiki.squid-cache.org/SquidFaq/OperatingSquid`
and deleted `swap.state` to trigger cache objects validation.
I re-read the instructions again, and I think that I just sped up what would have happened eventually.

Thanks again.
