### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by mrahmadt** [diladele/squid-ubuntu#3]
Hello

Can I use this instruction with Ubuntu serve 18.04?

Thanks

**Comment by ra-at-diladele-com** [comment]
I believe yes. If something does not work, please say so.

Best regards,
Rafael Akchurin

Op 26 aug. 2018 om 21:53 heeft Aft <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hello

Can I use this instruction with Ubuntu serve 18.04?

Thanks
