### ISSUE TITLE
Support for Ubuntu 14.04

### ISSUE THREAD

**Issue by shyamkhakhar9** [diladele/squid-ubuntu#5]
Hello,

Can I use this for ubuntu 14.04?

Thanks,

**Comment by ra-at-diladele-com** [comment]
Nope unfortunately only Ubuntu 18 (version 7+) and Ubuntu 16 (version 6.4)

**Comment by shyamkhakhar9** [comment]
Can you suggest anything where I can use squid 4 with ubuntu 14.04?

**Comment by ra-at-diladele-com** [comment]
I have not tried. Maybe ask Squid developers? Or try yourself creatively adjusting our instructions from Ubuntu 16?

**Comment by shyamkhakhar9** [comment]
Okay thanks for your quick reply.
