### ISSUE TITLE
warning info：munual installation for ubuntu 16

### ISSUE THREAD

**Issue by lukemin** [diladele/squid-ubuntu#8]
bash 03_build_ecap.sh
can not execute this sh.
waring info :
permission denied！

**Comment by ra-at-diladele-com** [comment]
Hello lukemin, I am not sure why you would get the error "permission denied". The 03_* file is a simple text file.. please try opening it using vi for example and see what is inside. Also make sure you own this file (use chown).

**Comment by lukemin** [comment]
I always use root on my vps. but 03_* can not be executed as root. so I created a new user, when I executed it, I got the warning info.

**Comment by ra-at-diladele-com** [comment]
Aah, ok. Indeed we try to compile as normal user not root. But if you open the 03_ file and remove the check for “not_root” it might also be compiled as a root user. I just never tried.

**Comment by lukemin** [comment]
thanks for your help.
