### ISSUE TITLE
No ssl_crtd?

### ISSUE THREAD

**Issue by dbsanfte** [diladele/squid-ubuntu#9]
ssl_crtd is not included in this package. Is it not compiled for ssl support?

**Comment by ra-at-diladele-com** [comment]
It was renamed by the Squid team, see release notes for Squid 4.

Best regards,
Rafael Akchurin

Op 10 jul. 2019 om 12:05 heeft David Sanftenberg <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


ssl_crtd is not included in this package. Is it not compiled for ssl support?
